# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test
      run: ./mvnw test
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{runner.os}}-sonar
        restore-keys: ${{runner.os}}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{runner.os}}-m2-${{ hashFiles('**/pom.xml')}}
        restore-keys: ${{runner.os}}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHU_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw clean install sonar:sonar package -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}} -Dsonar.login=${{secrets.SONAR_TOKEN}}
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: core-abstract-sample-${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}
        path: ./controller/target


  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        dontuseforce: false
